### PR TITLE
Fix possible XSS attack on user input

### PR DESCRIPTION
**Pull request by simahawk**
It's possible to fill forms with html
or JS scripts that could be executed on the server.

Replace cgi.escape with werkzeug.utils.escape.

Replaces #107

### CODE REVIEW

**Comment by hbrunn** [comment]
@simahawk does that mean I can never consume an unescaped `<` in my controllers using `cms_form`? Are you sure we're not fixing another problem somewhere, where user input is printed back on the website unescaped?

**Comment by simahawk** [comment]
@hbrunn sorry, I missed your comment.

To be honest, I opted for optimistic merge, likely too early. After thinking again about this I'd like to go for an optional escaping using a proper marshaller.

I implemented it here in my ongoing migration for v13 https://github.com/simahawk/website-cms/commit/ef69fb99f6163d7da529be37d8840822718eb1df

I'll backport it to v11 if ok. What do you think?

@Nooka10 would you mind to provide your use case?

**Comment by hbrunn** [comment]
this looks great to me

**Pull request merged**
