### PR TITLE
[fix] transifex setup

### PR DESCRIPTION
**Pull request by simahawk**
Reasons:

* no project on transifex for this repo
* tests are failing because of this (see https://github.com/OCA/website-cms/issues/7) and we cannot merge all the PRs that ready since a while
* we don't know if we are going to keep transifex for OCA at all
  See https://odoo-community.org/groups/contributors-15/contributors-50809?mode=date&date_begin=&date_end=
  and https://github.com/OCA/maintainer-quality-tools/issues/194#issue-79502151

### CODE REVIEW

**Comment by pedrobaeza** [comment]
No need to disable. I'm back from holidays and I'm going to provide you with the key during the day.

**Comment by simahawk** [comment]
@pedrobaeza ok, tnx. This issue blocks everything :/

**Comment by pedrobaeza** [comment]
@simahawk this is what you have to add to .travis.yml:

```
  secure: "Kk+GKDcTNayEcBj7zJXndcerUeEnRi4LpYaUcGDc6K+rBrNROHMKoEBW3EWNwCGIxa+BhzZGVlCACMa9wpChilfKBfT1r+2WMnILCj6dQzku3elEi0g6DO8M5/L6i64iG3PUh05uB/nN4EFDeDJp76Roof3YpaMyBnU2Hr8Z7dnbYYcxVDTSXRnHf6lYMKbbbMjp6qTQlFZwrnqic0TdmgpGUZJFGwP+NWO01/S6VrY0s6GvQvcBvY6ZGNZdEGr9OFspAm6q00rAHXf1b/PG0Sc5vJoFtWr1AtdcL048D2oWll5CCa+jHaWVfUOjiIgEs2U86zr9XC8FWxb84jkNnamEZ/kmc37bhszIVxzv5afpAqbjNqfkJcfUoMFkbNvAQ99BpolATdYYLMNcvZNEU/EdenJM5hLA7eMGzBWJWrlMqQ1JP2rVsXsTCHN5ypyJg2R1CGbCU6plB6Hnvi+o/M2L230iuIOV5Gh3ybokh8q210nA6MjEwnSBFN9Ks0SiW6nmejKcWmUyDnWNV268+tMHMtbovKQgLx6F3OJoh+smigA2zMNHpuziTQq9WMoorpVaguP1NuoZQJypyl6/hnIpiEMExTvkVd4oAQ1Ml9Fb9GP9ySozkciCdfwbW/bLPe0MLjsacVSCGixfBAEn5/iir+CuCVB6TgX4tU1kh5Y="
```

**Comment by simahawk** [comment]
@pedrobaeza should be ok now. Can you merge this? (I cannot)

**Pull request merged**
