### PR TITLE
[MIG][11] cms_delete_content + cms_status_message

### PR DESCRIPTION
**Pull request by simahawk**
replacing https://github.com/OCA/website-cms/pull/32 (parts of)

### CODE REVIEW

**Comment by simahawk** [comment]
I included status message too as it's a dependency and is not that much to review

**Review by remytms — APPROVED** [review]
Seems ok for me. :) Thanks for your work.

**Comment by simahawk** [comment]
runbot is red but it's actually yellow... probably due to the warning on missing phonenumbers lib (totally unrelated)

**Comment by astirpe** [comment]
@simahawk That runbot warning is on all the latest PRs. Do you know who could fix it? Or at least do you know someone we can address this issue to?

**Review by tschanzt — APPROVED** [review]
looks good to me.

**Comment by simahawk** [comment]
@astirpe FYI thanks to recent updates it's green now. Merging \o/

**Pull request merged**
