### PR TITLE
[10.0] cms_form: fix search domain rule handling w/ no value

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@grindtildeath check linting pls

**Comment by grindtildeath** [comment]
@simahawk Lint errors are unrelated to this change...

**Comment by simahawk** [comment]
this should fix it https://github.com/OCA/website-cms/pull/97

**Review by Tonow-c2c — APPROVED** [review]
LGTM just code review

**Review by leemannd — APPROVED** [review]
Not sure at all. Not an expert on this topic

**Comment by yvaucher** [comment]
Linting was fixed there, I'm merging

https://github.com/OCA/website-cms/commit/e50a7d3dafd44bda21b16310b8445a555b57e5e1

**Comment by simahawk** [comment]
@grindtildeath the builds fails on travis setup (likely for non pinned version of PG). I updated travis conf here https://github.com/OCA/website-cms/pull/108 let's see if makes it happy.

**Comment by simahawk** [comment]
@grindtildeath merged, can you try rebase again pls?

**Pull request merged**
